---
title: "Visualization"
output:
  pdf_document:
    latex_engine: xelatex
---

```{r, include=FALSE}
# load packages
library(ggwordcloud)
library(here)
library(kableExtra)
library(knitr)
library(sf)
library(tidytext)
library(tidyverse)
```

```{r, include=FALSE}
# read dataset
data_loc <- read_rds(here::here("data/event_clean.rds"))
area <- read_rds(here::here("data/area.rds"))
data <- data_loc |> st_drop_geometry()
```

```{r, echo=FALSE}
# visualize table
table <- data |>
  distinct(categ, .keep_all = TRUE) |>
  mutate(
    categ = map_chr(categ, ~ paste(.x, collapse = ", ")),
    feat = map_chr(feat, ~ paste(.x, collapse = ", "))
  ) |>
  mutate(across(where(is.character), ~ str_sub(., 1, 15))) |>
  head(10)
kable(table, caption = "Representative events in the beach area") |>
  kable_styling()
```

```{r, echo=FALSE}
time <- data |>
  count(dat) |>
  ggplot(aes(x = dat, y = n)) +
  geom_line(color = "purple", alpha = 0.7) +
  geom_point(color = "purple", alpha = 0.7) +
  labs(title = "Daily number of events from Oct 2025 to Dec 2025",
       x = "Date", y = "Number of Events") +
  theme_minimal()
time
```

```{r, echo=FALSE}
map <- data_loc |>
  count(loc) |>
  ggplot() +
  geom_sf(data = area, fill = "lightblue", alpha = 0.5) +
  geom_sf(aes(geometry = loc, size = n),
          color = "red", alpha = 0.7, show.legend = FALSE) +
  scale_size_continuous(range = c(1, 6)) +
  labs(title = "Geographic distribution of events within the beach area",
       size = "Number of Events") + # Better legend title
  theme_void()
map
```

```{r, echo=FALSE}
categ <- data |>
  unnest(categ) |>
  count(categ) |>
  ggplot(aes(x = reorder(categ, n), y = n)) +
  geom_col(alpha = 0.7, fill = "steelblue") +
  coord_flip() +
  labs(title = "Number of events within each category", 
       x = "Category", y = "Count") +
  theme_minimal()
categ
```

```{r, include=FALSE}
word_freq <- data |>
  unnest_tokens(word, descript) |>
  count(word, sort = TRUE) |>
  anti_join(stop_words) |>
  head(30)
```

```{r, echo=FALSE}
ggplot(word_freq, aes(label = word, size = n, color = n)) +
  geom_text_wordcloud() +
  scale_size_area(max_size = 15) +
  scale_color_gradient(low = "orange", high = "darkblue") +
  labs(title = "Key themes from event descriptions") +
  theme_minimal()
```

```{r, echo=FALSE}
free <- data |>
  count(free) |>
  mutate(percentage = n / sum(n) * 100) |>
  ggplot(aes(x = "", y = n, fill = free)) +
  geom_bar(stat = "identity", width = 1) +
    scale_fill_manual(values = c("darkgreen", "firebrick")) +
  geom_text(aes(label = paste0(round(percentage, 2), "%")), 
            position = position_stack(vjust = 0.5)) +
  coord_polar("y", start = 0) +
  labs(title = "Proportion of free vs paid events") +
  theme_void()
free
```

```{r, echo=FALSE}
reserv <- data |>
  count(reserv) |>
  mutate(percentage = n / sum(n) * 100) |>
  ggplot(aes(x = "", y = n, fill = reserv)) +
  geom_bar(stat = "identity", width = 1) +
  scale_fill_manual(values = c("darkgreen", "firebrick")) +
  geom_text(aes(label = paste0(round(percentage, 2), "%")), 
            position = position_stack(vjust = 0.5)) +
  coord_polar("y", start = 0) +
  labs(title = "Proportion of reservation required vs not required events") +
  theme_void()
reserv
```

```{r, echo=FALSE}
feat <- data |>
  unnest(feat) |>
  count(feat) |>
  ggplot(aes(x = reorder(feat, n), y = n)) +
  geom_col(alpha = 0.7, fill = "steelblue") +
  coord_flip() +
  labs(title = "Number of events having each feature", 
       x = "Feature", y = "Count") +
  theme_minimal()
feat
```
